services:
  cinerama_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: cinerama_frontend
    ports:
      - "8080:8080"
    volumes:
      - .:/code/
      - /code/node_modules